services:
  # Backend (Django + Gunicorn)
  - type: web
    name: nce-backend-web
    plan: free
    region: oregon
    runtime: python
    buildCommand: "pip install -r django_backend/requirements.txt --no-input"
    startCommand: "./django_backend/render-start-web.sh"

  # Worker (Celery + Beat)
  - type: worker
    name: nce-backend-worker
    plan: free
    region: oregon
    runtime: python
    buildCommand: "pip install -r django_backend/requirements.txt --no-input"
    startCommand: "./django_backend/render-start-celery.sh"
