"""
URL configuration for nce_backend_tmp project.
"""

from pathlib import Path

from django.conf import settings
from django.contrib import admin
from django.http import HttpResponse
from django.urls import include, path
from django.views.static import serve as static_serve

from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("api/", include("mailing.urls")),
    path("api/schema/", SpectacularAPIView.as_view(), name="api-schema"),
    path("api/docs/", SpectacularSwaggerView.as_view(url_name="api-schema"), name="api-docs"),
]

# Serve Vite-built dist in dev (needed for /assets/*.css, /assets/*.js + index.html)
if settings.DEBUG:
    dist_dir = Path(__file__).resolve().parents[2] / "site-nceOutsourcing" / "dist"
    assets_dir = dist_dir / "assets"
    index_html_path = dist_dir / "index.html"

    def spa_index_response(request):
        if not index_html_path.exists():
            return HttpResponse("index.html not found", status=404)
        return HttpResponse(index_html_path.read_text(encoding="utf-8"), content_type="text/html")

    urlpatterns += [
        # Static assets generated by Vite (only if present)
        path("assets/<path:path>", static_serve, {"document_root": assets_dir}),
        # SPA fallback: serve index.html for any non-API route
        path("", spa_index_response),
        path("<path:path>", spa_index_response),
    ]
